/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { ExpenseUpdateManyWithoutUsersInput } from "./ExpenseUpdateManyWithoutUsersInput";
import { Type } from "class-transformer";
import { IncomeUpdateManyWithoutUsersInput } from "./IncomeUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => ExpenseUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ExpenseUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ExpenseUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  expenses?: ExpenseUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => IncomeUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => IncomeUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => IncomeUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  incomes?: IncomeUpdateManyWithoutUsersInput;
}

export { UserUpdateInput as UserUpdateInput };
